[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python simple_main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"